// Package icon defines Nerd Font icon constants used throughout the TUI.
package icon

// Icons from https://www.nerdfonts.com/cheat-sheet
// nf-oct family

const (
	Alert      = " "
	AlertFill  = " "
	Approval   = "󰄴 "
	ArrowRight = "->"
	ArrowLeft  = "<-"
	ArrowDown  = ""
	Dash       = " "
	Diff       = " "
	Discussion = " "
	Dot        = " "
	Check      = " "
	Cross      = " "
	Clock      = " "
	Conflict   = " "
	// Conflict     = "󱒼   "
	Update       = "󰚰 "
	Time         = " "
	Rebase       = " "
	Merge        = " "
	Mergeable    = " "
	Edit         = " "
	User         = " "
	UserApproval = " "
	UserUpdate   = " "
	Plus         = " "
	Pipeline     = " "
	Gear         = " "
	Empty        = ""
	CircleCheck  = " "
	CircleCross  = " "
	// CircleCancel   = "󰜺 "
	CircleCancel   = " "
	CirclePause    = " "
	CircleDash     = " "
	CircleDot      = " "
	CirclePlay     = " "
	CircleSkip     = " "
	CircleQuestion = " "
	CircleRunning  = "󰪢 "
	Circle         = " "
	Gitlab         = " "
)
