package tui

import (
	"charm.land/lipgloss/v2"
	"github.com/felipeospina21/tuishell/style"
)

var presets = map[string]style.Theme{
	// ── Catppuccin Mocha (dark) ──
	"catppuccin-mocha": {
		Primary:       lipgloss.Color("#89b4fa"),
		PrimaryBright: lipgloss.Color("#b4befe"),
		PrimaryFg:     lipgloss.Color("#cdd6f4"),
		PrimaryDim:    lipgloss.Color("#45475a"),

		Info:          lipgloss.Color("#74c7ec"),
		InfoBright:    lipgloss.Color("#89dceb"),
		Success:       lipgloss.Color("#a6e3a1"),
		SuccessBright: lipgloss.Color("#94e2d5"),
		Danger:        lipgloss.Color("#f38ba8"),
		DangerBright:  lipgloss.Color("#eba0ac"),
		Warning:       lipgloss.Color("#f9e2af"),
		WarningBright: lipgloss.Color("#fab387"),
		Caution:       lipgloss.Color("#fab387"),

		Text:            lipgloss.Color("#cdd6f4"),
		TextInverse:     lipgloss.Color("#11111b"),
		TextDimmed:      lipgloss.Color("#a6adc8"),
		Muted:           lipgloss.Color("#9399b2"),
		Dim:             lipgloss.Color("#6c7086"),
		Border:          lipgloss.Color("#585b70"),
		ModalBorder:     lipgloss.Color("#7f849c"),
		SurfaceDim:      lipgloss.Color("#1e1e2e"),
		SelectionBorder: lipgloss.Color("#cba6f7"),

		StatusText:    lipgloss.Color("#cdd6f4"),
		StatusNormal:  lipgloss.Color("#45475a"),
		StatusLoading: lipgloss.Color("#94e2d5"),
		StatusError:   lipgloss.Color("#f38ba8"),
		StatusDev:     lipgloss.Color("#a6e3a1"),
		StatusAccent1: lipgloss.Color("#cba6f7"),
		StatusAccent2: lipgloss.Color("#b4befe"),
	},

	// ── Catppuccin Macchiato ──
	"catppuccin-macchiato": {
		Primary:       lipgloss.Color("#8aadf4"),
		PrimaryBright: lipgloss.Color("#b7bdf8"),
		PrimaryFg:     lipgloss.Color("#cad3f5"),
		PrimaryDim:    lipgloss.Color("#494d64"),

		Info:          lipgloss.Color("#7dc4e4"),
		InfoBright:    lipgloss.Color("#91d7e3"),
		Success:       lipgloss.Color("#a6da95"),
		SuccessBright: lipgloss.Color("#8bd5ca"),
		Danger:        lipgloss.Color("#ed8796"),
		DangerBright:  lipgloss.Color("#ee99a0"),
		Warning:       lipgloss.Color("#eed49f"),
		WarningBright: lipgloss.Color("#f5a97f"),
		Caution:       lipgloss.Color("#f5a97f"),

		Text:            lipgloss.Color("#cad3f5"),
		TextInverse:     lipgloss.Color("#181926"),
		TextDimmed:      lipgloss.Color("#a5adcb"),
		Muted:           lipgloss.Color("#939ab7"),
		Dim:             lipgloss.Color("#6e738d"),
		Border:          lipgloss.Color("#5b6078"),
		ModalBorder:     lipgloss.Color("#8087a2"),
		SurfaceDim:      lipgloss.Color("#24273a"),
		SelectionBorder: lipgloss.Color("#c6a0f6"),

		StatusText:    lipgloss.Color("#cad3f5"),
		StatusNormal:  lipgloss.Color("#494d64"),
		StatusLoading: lipgloss.Color("#8bd5ca"),
		StatusError:   lipgloss.Color("#ed8796"),
		StatusDev:     lipgloss.Color("#a6da95"),
		StatusAccent1: lipgloss.Color("#c6a0f6"),
		StatusAccent2: lipgloss.Color("#b7bdf8"),
	},

	// ── Catppuccin Frappé ──
	"catppuccin-frappe": {
		Primary:       lipgloss.Color("#8caaee"),
		PrimaryBright: lipgloss.Color("#babbf1"),
		PrimaryFg:     lipgloss.Color("#c6d0f5"),
		PrimaryDim:    lipgloss.Color("#51576d"),

		Info:          lipgloss.Color("#85c1dc"),
		InfoBright:    lipgloss.Color("#99d1db"),
		Success:       lipgloss.Color("#a6d189"),
		SuccessBright: lipgloss.Color("#81c8be"),
		Danger:        lipgloss.Color("#e78284"),
		DangerBright:  lipgloss.Color("#ea999c"),
		Warning:       lipgloss.Color("#e5c890"),
		WarningBright: lipgloss.Color("#ef9f76"),
		Caution:       lipgloss.Color("#ef9f76"),

		Text:            lipgloss.Color("#c6d0f5"),
		TextInverse:     lipgloss.Color("#232634"),
		TextDimmed:      lipgloss.Color("#a5adce"),
		Muted:           lipgloss.Color("#949cbb"),
		Dim:             lipgloss.Color("#737994"),
		Border:          lipgloss.Color("#626880"),
		ModalBorder:     lipgloss.Color("#838ba7"),
		SurfaceDim:      lipgloss.Color("#303446"),
		SelectionBorder: lipgloss.Color("#ca9ee6"),

		StatusText:    lipgloss.Color("#c6d0f5"),
		StatusNormal:  lipgloss.Color("#51576d"),
		StatusLoading: lipgloss.Color("#81c8be"),
		StatusError:   lipgloss.Color("#e78284"),
		StatusDev:     lipgloss.Color("#a6d189"),
		StatusAccent1: lipgloss.Color("#ca9ee6"),
		StatusAccent2: lipgloss.Color("#babbf1"),
	},

	// ── Catppuccin Latte (light) ──
	"catppuccin-latte": {
		Primary:       lipgloss.Color("#1e66f5"),
		PrimaryBright: lipgloss.Color("#7287fd"),
		PrimaryFg:     lipgloss.Color("#4c4f69"),
		PrimaryDim:    lipgloss.Color("#bcc0cc"),

		Info:          lipgloss.Color("#209fb5"),
		InfoBright:    lipgloss.Color("#04a5e5"),
		Success:       lipgloss.Color("#40a02b"),
		SuccessBright: lipgloss.Color("#179299"),
		Danger:        lipgloss.Color("#d20f39"),
		DangerBright:  lipgloss.Color("#e64553"),
		Warning:       lipgloss.Color("#df8e1d"),
		WarningBright: lipgloss.Color("#fe640b"),
		Caution:       lipgloss.Color("#fe640b"),

		Text:            lipgloss.Color("#4c4f69"),
		TextInverse:     lipgloss.Color("#eff1f5"),
		TextDimmed:      lipgloss.Color("#6c6f85"),
		Muted:           lipgloss.Color("#7c7f93"),
		Dim:             lipgloss.Color("#9ca0b0"),
		Border:          lipgloss.Color("#acb0be"),
		ModalBorder:     lipgloss.Color("#8c8fa1"),
		SurfaceDim:      lipgloss.Color("#eff1f5"),
		SelectionBorder: lipgloss.Color("#8839ef"),

		StatusText:    lipgloss.Color("#eff1f5"),
		StatusNormal:  lipgloss.Color("#bcc0cc"),
		StatusLoading: lipgloss.Color("#179299"),
		StatusError:   lipgloss.Color("#d20f39"),
		StatusDev:     lipgloss.Color("#40a02b"),
		StatusAccent1: lipgloss.Color("#8839ef"),
		StatusAccent2: lipgloss.Color("#7287fd"),
	},

	// ── Rosé Pine ──
	"rose-pine": {
		Primary:       lipgloss.Color("#c4a7e7"),
		PrimaryBright: lipgloss.Color("#ebbcba"),
		PrimaryFg:     lipgloss.Color("#e0def4"),
		PrimaryDim:    lipgloss.Color("#26233a"),

		Info:          lipgloss.Color("#9ccfd8"),
		InfoBright:    lipgloss.Color("#c4a7e7"),
		Success:       lipgloss.Color("#9ccfd8"),
		SuccessBright: lipgloss.Color("#3e8fb0"),
		Danger:        lipgloss.Color("#eb6f92"),
		DangerBright:  lipgloss.Color("#eb6f92"),
		Warning:       lipgloss.Color("#f6c177"),
		WarningBright: lipgloss.Color("#f6c177"),
		Caution:       lipgloss.Color("#ebbcba"),

		Text:            lipgloss.Color("#e0def4"),
		TextInverse:     lipgloss.Color("#191724"),
		TextDimmed:      lipgloss.Color("#908caa"),
		Muted:           lipgloss.Color("#6e6a86"),
		Dim:             lipgloss.Color("#524f67"),
		Border:          lipgloss.Color("#403d52"),
		ModalBorder:     lipgloss.Color("#524f67"),
		SurfaceDim:      lipgloss.Color("#191724"),
		SelectionBorder: lipgloss.Color("#c4a7e7"),

		StatusText:    lipgloss.Color("#e0def4"),
		StatusNormal:  lipgloss.Color("#21202e"),
		StatusLoading: lipgloss.Color("#9ccfd8"),
		StatusError:   lipgloss.Color("#eb6f92"),
		StatusDev:     lipgloss.Color("#3e8fb0"),
		StatusAccent1: lipgloss.Color("#c4a7e7"),
		StatusAccent2: lipgloss.Color("#ebbcba"),
	},

	// ── Tokyo Night ──
	"tokyo-night": {
		Primary:       lipgloss.Color("#7aa2f7"),
		PrimaryBright: lipgloss.Color("#2ac3de"),
		PrimaryFg:     lipgloss.Color("#c0caf5"),
		PrimaryDim:    lipgloss.Color("#3b4261"),

		Info:          lipgloss.Color("#7dcfff"),
		InfoBright:    lipgloss.Color("#2ac3de"),
		Success:       lipgloss.Color("#9ece6a"),
		SuccessBright: lipgloss.Color("#73daca"),
		Danger:        lipgloss.Color("#f7768e"),
		DangerBright:  lipgloss.Color("#ff9e64"),
		Warning:       lipgloss.Color("#e0af68"),
		WarningBright: lipgloss.Color("#ff9e64"),
		Caution:       lipgloss.Color("#ff9e64"),

		Text:            lipgloss.Color("#c0caf5"),
		TextInverse:     lipgloss.Color("#1a1b26"),
		TextDimmed:      lipgloss.Color("#a9b1d6"),
		Muted:           lipgloss.Color("#565f89"),
		Dim:             lipgloss.Color("#3b4261"),
		Border:          lipgloss.Color("#292e42"),
		ModalBorder:     lipgloss.Color("#565f89"),
		SurfaceDim:      lipgloss.Color("#1a1b26"),
		SelectionBorder: lipgloss.Color("#bb9af7"),

		StatusText:    lipgloss.Color("#c0caf5"),
		StatusNormal:  lipgloss.Color("#292e42"),
		StatusLoading: lipgloss.Color("#73daca"),
		StatusError:   lipgloss.Color("#f7768e"),
		StatusDev:     lipgloss.Color("#9ece6a"),
		StatusAccent1: lipgloss.Color("#bb9af7"),
		StatusAccent2: lipgloss.Color("#7aa2f7"),
	},

	// ── Dracula ──
	"dracula": {
		Primary:       lipgloss.Color("#bd93f9"),
		PrimaryBright: lipgloss.Color("#ff79c6"),
		PrimaryFg:     lipgloss.Color("#f8f8f2"),
		PrimaryDim:    lipgloss.Color("#44475a"),

		Info:          lipgloss.Color("#8be9fd"),
		InfoBright:    lipgloss.Color("#bd93f9"),
		Success:       lipgloss.Color("#50fa7b"),
		SuccessBright: lipgloss.Color("#50fa7b"),
		Danger:        lipgloss.Color("#ff5555"),
		DangerBright:  lipgloss.Color("#ff6e6e"),
		Warning:       lipgloss.Color("#f1fa8c"),
		WarningBright: lipgloss.Color("#ffb86c"),
		Caution:       lipgloss.Color("#ffb86c"),

		Text:            lipgloss.Color("#f8f8f2"),
		TextInverse:     lipgloss.Color("#282a36"),
		TextDimmed:      lipgloss.Color("#bfbfbf"),
		Muted:           lipgloss.Color("#6272a4"),
		Dim:             lipgloss.Color("#44475a"),
		Border:          lipgloss.Color("#44475a"),
		ModalBorder:     lipgloss.Color("#6272a4"),
		SurfaceDim:      lipgloss.Color("#282a36"),
		SelectionBorder: lipgloss.Color("#ff79c6"),

		StatusText:    lipgloss.Color("#f8f8f2"),
		StatusNormal:  lipgloss.Color("#44475a"),
		StatusLoading: lipgloss.Color("#8be9fd"),
		StatusError:   lipgloss.Color("#ff5555"),
		StatusDev:     lipgloss.Color("#50fa7b"),
		StatusAccent1: lipgloss.Color("#bd93f9"),
		StatusAccent2: lipgloss.Color("#ff79c6"),
	},
}
